

interface Props { isOpen: boolean; onClose: () => void; }
export default function ViewReportsModal({ isOpen, onClose }: Props) {
  if (!isOpen) return null;
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-4"><div className="app-card max-w-md p-7"><div className="flex items-start justify-between gap-4"><div><p className="app-label">Event reporting</p><h2 className="app-page-title">Event attendance reports</h2></div><button type="button" onClick={onClose} className="text-white/50">Close</button></div><p className="mt-4 text-sm leading-6 text-white/55">Personal and authorized event attendance PDFs are available from the event workspace. Reports are generated by the server for the signed-in account.</p><button type="button" onClick={onClose} className="app-button-primary mt-6">Return to event workspace</button></div></div>;
}
